package org.online_shop.enums;

public enum Response {
    USER_EXISTS,
    USER_NOT_FOUND,
    USER_CREATED_SUCCESSFULLY,
    USER_UPDATED_SUCCESSFULLY,
    USER_DELETED_SUCCESSFULLY,
    SOMETHING_WENT_WRONG,
    INCORRECT_EMAIL,
    INCORRECT_PASSWORD,
    PASSWORDS_DO_NOT_MATCH,
    PASSWORD_UPDATED_SUCCESSFULLY,
    LOGIN_SUCCESSFUL,
    PRODUCT_CREATED_SUCCESSFULLY,
    PRODUCT_NOT_FOUND,
    PRODUCT_UPDATED_SUCCESSFULLY,
    PRODUCT_DELETED_SUCCESSFULLY,
    CATEGORY_CREATED_SUCCESSFULLLY,
    CATEGORY_NOT_FOUND,
    CATEGORY_UPDATED_SUCCESSFULLY,
    CATEGORY_DELETED_SUCCESSFULLY,
    ALL_PRODUCTS_DELETED_SUCCESSFULLY,
    ALL_CATEGORIES_DELETED_SUCCESSFULLY
}
